Add SoyeeChoi's record ...
develop-with-google-kor/dwg-kor-github-2018 pull request #8
Opened 2016-12-31 02:58 UTC by Csoyee

add Soyee, Choi's record...

2016-12-31 09:21 UTC, develop-with-google-kor requested changes
one nit, please take a look.

2016-12-31 09:21 UTC, develop-with-google-kor commented on codelab_pull_request.txt
> +SoyeeChoid: https://github.com/Csoyee/codelab1.git
please remove '.git'. That parts is not necessary.

2016-12-31 10:35 UTC, Csoyee commented
I removed unnecessary part of the 'url' requested.

2017-01-02 02:36 UTC, develop-with-google-kor approved these changes

2017-01-02 02:37 UTC, merged